### ISSUE TITLE
Add search functionality to filter icons by name

### ISSUE THREAD

**Issue by hamidrezaramzani** [mortezasabihi/iconsans#11]
**Is your feature request related to a problem? Please describe**
Yes, the feature request is related to the problem of users having difficulty finding icons in the icon library when there are many icons to choose from. Without a search functionality, users may have to manually scroll through the entire library to find the icon they need, which can be time-consuming and frustrating.

**Describe the solution you'd like**
The solution I'd like is to add a search functionality to the icon library that allows users to filter icons by their names. This would involve adding a search input to the library interface and implementing JavaScript code that interacts with the existing icon library to display only the icons that match the entered search term.

**Describe alternatives you've considered**
Nothing

**Aditional Context**
Nothing

**Comment by mortezasabihi** [comment]
@hamidrezaramzani 
Thanks for the PR.
