### ISSUE TITLE
Make search field clearable

### ISSUE THREAD

**Issue by amirhoseinsalimi** [mortezasabihi/iconsans#22]
**Is your feature request related to a problem? Please describe.**
When searching for icons, having a standard "x" button to clear the search field is good.

**Describe the solution you'd like**
From a technical point of view, hanging the input type from "text" to "search" should do the work.

**Describe alternatives you've considered**
Right now, it's possible to clear the search field only by wasting some keystrokes on "Backspace" key.

**Additional context**
![Screenshot from 2023-05-23 20-14-47](https://github.com/mortezasabihi/iconsans/assets/25503371/8ef2329b-7314-4018-9709-637476fdf60d)

I would like to work on this issue.

**Comment by mortezasabihi** [comment]
@amirhoseinsalimi Nice, I appericiate it.
